// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RoadMaintenance.FaultLogging.Specs.UpdateGPSCoordinates
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Update the GPS Coordinates for a fault")]
    public partial class UpdateTheGPSCoordinatesForAFaultFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UpdateGPSCoordinates.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Update the GPS Coordinates for a fault", "In order for a technician to more easily locate a fault location\nAs a call-center" +
                    " operator\nI want to be able to update the GPS coordinates for a fault", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update the GPS coordinates of an open fault: coordinate format spaces")]
        [NUnit.Framework.CategoryAttribute("greenPath")]
        public virtual void UpdateTheGPSCoordinatesOfAnOpenFaultCoordinateFormatSpaces()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update the GPS coordinates of an open fault: coordinate format spaces", new string[] {
                        "greenPath"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am on the Add GPS Coordinates page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("the fault I am editing has the Id \'202947AF-130F-4494-8C50-DB84A93648E1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("I enter \'33 34 35 W\' as the longitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("I enter \'56 21 23 S\' as the latitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table1.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table1.AddRow(new string[] {
                        "46BF992F-B00C-4D76-BDD0-CCB6B993E8EF",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 12
 testRunner.And("These faults exist", ((string)(null)), table1, "And ");
#line 16
 testRunner.When("I press the Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
 testRunner.And("I perform a find for this fault id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table2.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "56 21 23 S",
                        "33 34 35 W",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 18
 testRunner.Then("The results should be", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update the GPS coordinates of an open fault: coordinate format dashes")]
        public virtual void UpdateTheGPSCoordinatesOfAnOpenFaultCoordinateFormatDashes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update the GPS coordinates of an open fault: coordinate format dashes", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I am on the Add GPS Coordinates page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("the fault I am editing has the Id \'202947AF-130F-4494-8C50-DB84A93648E1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("I enter \'33-34-35-W\' as the longitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I enter \'56-21-23-S\' as the latitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table3.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table3.AddRow(new string[] {
                        "46BF992F-B00C-4D76-BDD0-CCB6B993E8EF",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 27
 testRunner.And("These faults exist", ((string)(null)), table3, "And ");
#line 31
 testRunner.When("I press the Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.And("I perform a find for this fault id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table4.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "56 21 23 S",
                        "33 34 35 W",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 33
 testRunner.Then("The results should be", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update the GPS coordinates of an open fault: coordinate format backslashes")]
        public virtual void UpdateTheGPSCoordinatesOfAnOpenFaultCoordinateFormatBackslashes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update the GPS coordinates of an open fault: coordinate format backslashes", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I am on the Add GPS Coordinates page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
 testRunner.And("the fault I am editing has the Id \'202947AF-130F-4494-8C50-DB84A93648E1\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I enter \'33/34/35/W\' as the longitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.And("I enter \'56/21/23/S\' as the latitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table5.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table5.AddRow(new string[] {
                        "46BF992F-B00C-4D76-BDD0-CCB6B993E8EF",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 42
 testRunner.And("These faults exist", ((string)(null)), table5, "And ");
#line 46
 testRunner.When("I press the Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 47
 testRunner.And("I perform a find for this fault id", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table6.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "56 21 23 S",
                        "33 34 35 W",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 48
 testRunner.Then("The results should be", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update the GPS coordinates of a fault where the status is Closed")]
        public virtual void UpdateTheGPSCoordinatesOfAFaultWhereTheStatusIsClosed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update the GPS coordinates of a fault where the status is Closed", ((string[])(null)));
#line 52
this.ScenarioSetup(scenarioInfo);
#line 53
 testRunner.Given("I am on the Add GPS Coordinates page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 54
 testRunner.And("the fault I am editing has the Id \'46BF992F-B00C-4D76-BDD0-CCB6B993E8EF\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
 testRunner.And("I enter \'33/34/35/W\' as the longitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 56
 testRunner.And("I enter \'56/21/23/S\' as the latitude", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Latitude",
                        "Longitude",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table7.AddRow(new string[] {
                        "202947AF-130F-4494-8C50-DB84A93648E1",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table7.AddRow(new string[] {
                        "46BF992F-B00C-4D76-BDD0-CCB6B993E8EF",
                        "",
                        "",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 57
 testRunner.And("These faults exist", ((string)(null)), table7, "And ");
#line 61
 testRunner.When("I press the Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 62
 testRunner.Then("an InvalidOperationException should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
