// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RoadMaintenance.FaultLogging.Specs.SearchFaults
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SearchFaults")]
    public partial class SearchFaultsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SearchFaults.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SearchFaults", "In order to ensure existing faults aren\'t duplicated\r\nAs a call center operator\r\n" +
                    "I want to enter a street address, cross-street address, suburb or fault type and" +
                    " receive a list of all open and recently closed faults containing that informati" +
                    "on.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by street name")]
        [NUnit.Framework.CategoryAttribute("GreenPath")]
        public virtual void FindOpenAndRecentlyClosedFaultsByStreetName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by street name", new string[] {
                        "GreenPath"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("I enter \'Hill Street\' as the street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table1.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table1.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table1.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table1.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table1.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table1.AddRow(new string[] {
                        "6",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table1.AddRow(new string[] {
                        "8",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table1.AddRow(new string[] {
                        "9",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table1.AddRow(new string[] {
                        "11",
                        "Republic Road",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table1.AddRow(new string[] {
                        "13",
                        "Republic Road",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 12
 testRunner.And("These faults exist", ((string)(null)), table1, "And ");
#line 24
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table2.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table2.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table2.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table2.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table2.AddRow(new string[] {
                        "6",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table2.AddRow(new string[] {
                        "8",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
#line 25
 testRunner.Then("The results should be", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by cross street name")]
        public virtual void FindOpenAndRecentlyClosedFaultsByCrossStreetName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by cross street name", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.And("I enter \'Hill Street\' as the cross street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table3.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table3.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table3.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table3.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table3.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table3.AddRow(new string[] {
                        "6",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table3.AddRow(new string[] {
                        "8",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table3.AddRow(new string[] {
                        "9",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table3.AddRow(new string[] {
                        "11",
                        "Republic Road",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table3.AddRow(new string[] {
                        "13",
                        "Republic Road",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
#line 39
 testRunner.And("These faults exist", ((string)(null)), table3, "And ");
#line 51
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table4.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table4.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table4.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table4.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table4.AddRow(new string[] {
                        "6",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table4.AddRow(new string[] {
                        "8",
                        "Fern Street",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
#line 52
 testRunner.Then("The results should be", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by suburb name")]
        public virtual void FindOpenAndRecentlyClosedFaultsBySuburbName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by suburb name", ((string[])(null)));
#line 61
this.ScenarioSetup(scenarioInfo);
#line 62
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
 testRunner.And("I enter \'Sandton\' as the suburb name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table5.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        ""});
            table5.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        "2015-03-01"});
            table5.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        "2015-03-02"});
            table5.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "2",
                        "2015-03-01"});
            table5.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "2",
                        "2015-03-02"});
            table5.AddRow(new string[] {
                        "6",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table5.AddRow(new string[] {
                        "7",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 66
 testRunner.And("These faults exist", ((string)(null)), table5, "And ");
#line 75
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table6.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        ""});
            table6.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        "2015-03-01"});
            table6.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "2",
                        "2015-03-02"});
            table6.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "2",
                        "2015-03-02"});
#line 76
 testRunner.Then("The results should be", ((string)(null)), table6, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by fault type")]
        public virtual void FindOpenAndRecentlyClosedFaultsByFaultType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by fault type", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 85
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 86
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table7.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        ""});
            table7.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        "2015-03-01"});
            table7.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        "2015-03-02"});
            table7.AddRow(new string[] {
                        "4",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "1",
                        "2015-03-01"});
            table7.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "1",
                        "2015-03-02"});
            table7.AddRow(new string[] {
                        "6",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
            table7.AddRow(new string[] {
                        "7",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 87
 testRunner.And("These faults exist", ((string)(null)), table7, "And ");
#line 96
 testRunner.And("I select \'Pothole\' as the fault type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 97
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table8.AddRow(new string[] {
                        "1",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        ""});
            table8.AddRow(new string[] {
                        "2",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        "2015-03-01"});
            table8.AddRow(new string[] {
                        "3",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        "2015-03-02"});
            table8.AddRow(new string[] {
                        "5",
                        "Hill Street",
                        "Malabongwe Drive",
                        "Sandton",
                        "2196",
                        "4",
                        "1",
                        "2015-03-02"});
#line 98
 testRunner.Then("The results should be", ((string)(null)), table8, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by street and cross street")]
        public virtual void FindOpenAndRecentlyClosedFaultsByStreetAndCrossStreet()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by street and cross street", ((string[])(null)));
#line 105
this.ScenarioSetup(scenarioInfo);
#line 106
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 107
 testRunner.And("I enter \'Hill Street\' as the street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.And("I enter \'Fern Ave\' as the cross street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 109
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 110
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table9.AddRow(new string[] {
                        "01",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table9.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table9.AddRow(new string[] {
                        "03",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table9.AddRow(new string[] {
                        "05",
                        "Fern Ave",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table9.AddRow(new string[] {
                        "07",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table9.AddRow(new string[] {
                        "08",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table9.AddRow(new string[] {
                        "09",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table9.AddRow(new string[] {
                        "10",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
#line 111
 testRunner.And("These faults exist", ((string)(null)), table9, "And ");
#line 121
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table10.AddRow(new string[] {
                        "01",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table10.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table10.AddRow(new string[] {
                        "08",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table10.AddRow(new string[] {
                        "10",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
#line 122
 testRunner.Then("The results should be", ((string)(null)), table10, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by street and cross street and fault type")]
        public virtual void FindOpenAndRecentlyClosedFaultsByStreetAndCrossStreetAndFaultType()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by street and cross street and fault type", ((string[])(null)));
#line 129
this.ScenarioSetup(scenarioInfo);
#line 130
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 131
 testRunner.And("I enter \'Hill Street\' as the street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("I enter \'Fern Ave\' as the cross street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table11.AddRow(new string[] {
                        "01",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table11.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table11.AddRow(new string[] {
                        "03",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table11.AddRow(new string[] {
                        "05",
                        "Fern Ave",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table11.AddRow(new string[] {
                        "07",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table11.AddRow(new string[] {
                        "08",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table11.AddRow(new string[] {
                        "09",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table11.AddRow(new string[] {
                        "10",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table11.AddRow(new string[] {
                        "11",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table11.AddRow(new string[] {
                        "12",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "3",
                        "2015-03-02"});
            table11.AddRow(new string[] {
                        "13",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table11.AddRow(new string[] {
                        "14",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table11.AddRow(new string[] {
                        "15",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 135
 testRunner.And("These faults exist", ((string)(null)), table11, "And ");
#line 150
 testRunner.And("I select \'Pothole\' as the fault type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 151
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table12.AddRow(new string[] {
                        "01",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table12.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table12.AddRow(new string[] {
                        "08",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table12.AddRow(new string[] {
                        "10",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
#line 152
 testRunner.Then("The results should be", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Find open and recently closed faults by street and cross street and fault type an" +
            "d suburb name")]
        public virtual void FindOpenAndRecentlyClosedFaultsByStreetAndCrossStreetAndFaultTypeAndSuburbName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Find open and recently closed faults by street and cross street and fault type an" +
                    "d suburb name", ((string[])(null)));
#line 159
this.ScenarioSetup(scenarioInfo);
#line 160
 testRunner.Given("I am a \'CallCenterOperator\' user role", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 161
 testRunner.And("I enter \'Hill Street\' as the street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 162
 testRunner.And("I enter \'Fern Ave\' as the cross street name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 163
 testRunner.And("I enter \'Sandton\' as the suburb name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 164
 testRunner.And("The date today is \'2015-04-01\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 165
 testRunner.And("The recently closed fault logging search period is \'30\' days", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table13.AddRow(new string[] {
                        "01",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table13.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        ""});
            table13.AddRow(new string[] {
                        "03",
                        "Hill Street",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table13.AddRow(new string[] {
                        "05",
                        "Fern Ave",
                        "",
                        "Randburg",
                        "2194",
                        "1",
                        "1",
                        ""});
            table13.AddRow(new string[] {
                        "07",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table13.AddRow(new string[] {
                        "08",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table13.AddRow(new string[] {
                        "09",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-01"});
            table13.AddRow(new string[] {
                        "10",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "1",
                        "2015-03-02"});
            table13.AddRow(new string[] {
                        "11",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table13.AddRow(new string[] {
                        "12",
                        "Hill Street",
                        "Fern Ave",
                        "Randburg",
                        "2194",
                        "4",
                        "3",
                        "2015-03-02"});
            table13.AddRow(new string[] {
                        "13",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-01"});
            table13.AddRow(new string[] {
                        "14",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "4",
                        "2",
                        "2015-03-02"});
            table13.AddRow(new string[] {
                        "15",
                        "Fern Ave",
                        "Hill Street",
                        "Randburg",
                        "2194",
                        "1",
                        "2",
                        ""});
#line 166
 testRunner.And("These faults exist", ((string)(null)), table13, "And ");
#line 181
 testRunner.And("I select \'Pothole\' as the fault type", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 182
 testRunner.When("I press the Search button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Street",
                        "CrossStreet",
                        "Suburb",
                        "PostCode",
                        "StatusId",
                        "TypeId",
                        "DateCompleted"});
            table14.AddRow(new string[] {
                        "02",
                        "Fern Ave",
                        "Hill Street",
                        "Sandton",
                        "2196",
                        "1",
                        "1",
                        ""});
#line 183
 testRunner.Then("The results should be", ((string)(null)), table14, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
